### PR TITLE
Add placeholders for log examples

### PR DESCRIPTION
**Pull request by brson**
r? @dtolnay 

cc https://github.com/brson/rust-cookbook/issues/61

I didn't add the entry for the 'syslog' example because I don't know which crate implements log for the syslog.

### CODE REVIEW

**Comment by dtolnay** [comment]
Thanks! I don't think "command line" is the right category for these. Looks like crates.io has log and slog and env_logger under a category called ["debugging"](https://crates.io/categories/development-tools::debugging).

**Comment by budziq** [comment]
https://github.com/Geal/rust-syslog can be used as a backend for syslog
Minimal example:
 https://play.integer32.com/?gist=a21a9b6735f80d072ebea471840d2534&version=undefined

**Comment by brson** [comment]
Thanks @budzig I updated to include the syslog example, and changed the category.

**Comment by brson** [comment]
I'm going to just merge to get this deployed.

**Comment by brson** [comment]
Thanks @budziq

**Pull request merged**
