### PR TITLE
Add file-predicate example

### PR DESCRIPTION
**Pull request by luisbg**
This is to solve #125 

Happy to tweak this with any reviews, comments and ideas :smiley:

### CODE REVIEW

**Comment by dtolnay** [comment]
Thanks! Could you check why the build is failing?

**Comment by luisbg** [comment]
I think I know why it didn't build. Fixing it.

**Comment by luisbg** [comment]
Tests passed. I'm wondering if using unwrap() is good style or if I should do it differently.

Whatever you prefer @dtolnay

**Comment by dtolnay** [comment]
Unwrap is not good style. Check out [a note about error handling](https://brson.github.io/rust-cookbook/about.html#a-note-about-error-handling).

**Comment by luisbg** [comment]
Gotcha. Cleaning it now.

**Comment by dtolnay** [comment]
Nicely done!

**Pull request merged**
